name: build

# Run the workflow only when pushing to the master branch.
on:
  push:
    branches:
      - master

# Required because the workflow pushes the generated PDF
# back to the repository's build branch.
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install a minimal TeX Live distribution.  The installation
      # is automatically cached by zauguin/install-texlive.
      #
      # Add any additional TeX Live packages required by vitae.tex
      # to this list.
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          texlive_version: 2026
          packages: |
            scheme-basic
            collection-latexrecommended
            microtype
            mathpazo

      - name: Generate PDFs
        run: |
          make
          mkdir build
          mv -f vitae.pdf build

      # The purpose here is to replace the contents of
      # the target branch with the contents of the build
      # directory.  This is an NIH hack to avoid the use of
      # existing actions like s0/git-publish-subdir-action,
      # which is a 500+ SLOC mess written in node.js.
      - name: Push build to separate branch
        env:
          GIT_BRANCH: "build"
          GIT_MESSAGE: ""
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git switch "$GIT_BRANCH" || git switch --orphan "$GIT_BRANCH"

          # GitHub requires you to use a token for push access.
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Move .git to the build dir and recommit.
          mv .git ./build
          cd ./build
          git add .
          git commit --allow-empty-message -m "$GIT_MESSAGE"
          git push -u origin "$GIT_BRANCH" --force
